server:
  #端口号
  port: 8092

spring:
  application:
    name: producer-server

eureka:
  instance:
    hostname: localhost
    eureka-server-port: 8081
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.eureka-server-port}/eureka/
