server:
  #端口号
  port: 8100

spring:
  application:
    name: consumer-server

eureka:
  instance:
    hostname: localhost
    eureka-server-port: 8091
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.eureka-server-port}/eureka/

feign:
  hystrix:
    enabled: true