server:
  #端口号
  port: 8081

eureka:
  instance:
    hostname: localhost
  server:
    # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
    evictionIntervalTimerInMs: 5000
  client:
    # eureka.client.registerWithEureka ：表示是否将自己注册到Eureka Server，默认为true。
    # 由于当前这个应用就是Eureka Server，故而设为false
    registerWithEureka: false
    # eureka.client.fetchRegistry ：表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，
    # 不需要同步其他的Eureka Server节点的数据，故而设为false。
    fetchRegistry: false
    # eureka.client.serviceUrl.defaultZone ：设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/